version: '3.8'

services:
  web:
    build: .
    container_name: apache_web
    ports:
      - "9680:80"  # Web accessible on port 9680
    volumes:
      - ./web:/var/www/html  # Mount the web folder as Apache root
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "9606:3306"  # Expose MySQL on port 9606
    volumes:
      - db_data:/var/lib/mysql  # Persist database data
      - ./db/travian.sql:/docker-entrypoint-initdb.d/travian.sql  # Auto-seed database

volumes:
  db_data:
